language: node_js

node_js:
  - "8"
  - "10"
  - "12"

env:
  - INSTALL_JDK=1
  - INSTALL_JDK=0

before_install:
  - if [[ "$INSTALL_JDK" == "1" ]] ; then make install_jdk ; fi

install:
  - yarn install --production=true

script:
  - yarn add @authenio/samlify-xsd-schema-validator
  - yarn test

branches:
  only:
  - master
  - /^.*-alpha$/
  - /^.*-rc.*$/

after_success: npm run coverage